// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snkjquhfpjxiyfctjrme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNua2pxdWhmcGp4aXlmY3Rqcm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODA1NTgsImV4cCI6MjA3MTg1NjU1OH0.rZifq6dRRzW7wFk6LcWNwXJ4-W9lL3IyS-JHMfSSNb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});